name: Deploy Three-Tier App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H 65.1.129.49 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@65.1.129.49 << 'EOF'
            cd ~/3-tier-app || (git clone https://github.com/${{ github.repository }}.git 3-tier-app && cd 3-tier-app)
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up --build -d
          EOF
